UIverse-Team/UIverse-FE

package.json
src/app/layout.tsx
src/components/common/Breadcrumb/Breadcrumb.tsx
src/components/common/Button/Button.tsx
src/components/common/Button/TextButton.tsx
src/components/common/Checkbox/Checkbox.tsx
src/components/common/Dialog/Dialog.tsx
src/components/common/Divider/Divider.tsx
src/components/common/HelperLabel/HelperLabel.tsx
src/components/common/Input/Input.tsx
src/components/common/Radio/RadioGroup.tsx
src/components/common/Radio/RadioGroupItem.tsx
src/components/common/Tab/Tab.tsx
src/components/common/Textarea/Textarea.tsx
src/components/ui/PagationContainer.tsx
src/components/ui/accordion.tsx
src/components/ui/button.tsx
src/components/ui/dropdown-menu.tsx
src/components/ui/select.tsx
src/constants/queryKeys.ts
src/hooks/useDataMutation.ts
src/hooks/useFetchData.ts
src/lib/utils.ts
src/libs/tailwindcss/utils.ts
src/libs/tanstackQuery/PrefetchedQueryHydrationBoundary.tsx
src/libs/tanstackQuery/QueryClientProvider.tsx
src/libs/tanstackQuery/queryClient.ts
src/providers/Providers.tsx
yarn.lock

#81 
- tanstack query 설정
- tanstack query 사용 위한 훅, 상수, 컴포넌트 추가
어떤 변경 사항이 있나요?
관련 설명 위한 문서는 노션에 작성해놓았습니다.
https://www.notion.so/Next-js-Tanstack-Query-1c1cc686750c8047bb8ec33a609b98a1?pvs=4
읽어보고 잘 활용하시고, 질문 있으시면 직접 물어봐주세요.

[setting] tanstack query 설정

---

src/app/(auth)/login/page.tsx
src/app/(auth)/signup/page.tsx
src/app/(main)/layout.tsx
src/app/(main)/page.tsx
src/app/cart/layout.tsx
src/app/product/[id]/layout.tsx
src/app/product/[id]/page.tsx
src/components/layout/Container/Container.tsx
src/components/signup/AgreementForm.tsx
src/components/signup/EmailForm.tsx
src/components/signup/PasswordForm.tsx
src/components/signup/UserInfoForm.tsx
src/types/container/containerType.ts
src/types/multistep/multistep.ts

없음
타입 추가에 따른 리팩토링 및 컴포넌트명 통일
어떤 변경 사항이 있나요?
app 폴더 하위에 만들어지는 각 페이지의
- layout.tsx 컴포넌트의 이름은 [페이지명]Layout
- page.tsx 컴포넌트의 이름은 [페이지명]Page
로 통일해주세요.

[refact] 타입 추가에 따른 리팩토링 및 컴포넌트명 통일

---

src/components/common/Accordion/Accordion.tsx
src/components/common/Chip/Chip.tsx
src/components/ui/dropdown-menu.tsx

fix: vercel 배포 에러 수정 sharcn cn 경로 수정 및 delete svg 파일명 수정

---

src/app/api/product/[id]/route.ts

fix: vercel 배포 수정 params type error

---

next.config.ts
src/app/(main)/page.tsx
src/app/api/product/[id]/route.ts
src/app/product/[id]/page.tsx

feature: 에러 수정

---

src/app/api/product/[id]/route.ts

feature: 에러 수정 parmas Promise type으로 수정

---

src/hooks/useCart.tsx

fix: product type error

---

src/components/cart/CartItemForm.tsx

fix: cart localstorage error 해결

---

src/app/(main)/page.tsx

fix: force-dynamic 추가

---

src/app/cart/page.tsx
src/components/cart/CartItemForm.tsx
src/components/cart/CartPayForm.tsx

fix: localstorage ssr error

---

src/app/cart/page.tsx

fix: cart client convert server component

---

src/app/(main)/page.tsx
src/app/api/carts/guest/route.ts
src/app/api/carts/route.ts
src/app/product/[productId]/page.tsx
src/components/cart/CartItemForm.tsx
src/components/common/NumbericField/NumbericField.tsx
src/components/product/AllProducts.tsx
src/hooks/useCart.tsx
src/services/cartService.ts
src/services/productService.ts
src/types/Product/productsType.ts

#107 
- 클라이언트 컴포넌트 api router를 사용하여 서버 api 호출
어떤 변경 사항이 있나요?

feature: client api router

---

src/components/auth/login/MemberLogin.tsx
src/constants/routes.ts
src/middleware.ts
src/serverActions/auth/login/actions.ts
src/serverActions/auth/logout/actions.ts

[fix] token명이 같아서 생기는 에러 수정, 아이디/비밀번호 찾기 link 추가

---

src/app/(main)/page.tsx
src/app/api/products/popular/route.ts
src/components/product/AllProducts.tsx
src/constants/queryKeys.ts
src/services/productService.ts

fix: popularity timeout error 해결

---

src/app/(main)/page.tsx

fix: popularity time out eror 해결

---

src/app/api/products/popular/route.ts
src/services/productService.ts
src/util/httpClient.ts

fix: vercel http api 호출 에러 진행중

---

src/stores/user.ts

[fix] zustand persist hydrantion delete

---

src/app/(main)/layout.tsx
src/components/banner/EventBanner.tsx
src/components/layout/Container/Container.tsx
src/components/layout/Header/HamburgerMenu.tsx
src/components/layout/Header/Header.tsx
src/components/layout/Header/MenuNavList.tsx
src/types/container/containerType.ts

#141 
헤더 햄버거 메뉴 마크업 및 기능 구현
아직 카테고리 데이터 연동은 안 되어 mock 데이터 활용
어떤 변경 사항이 있나요?
카테고리 데이터는 추후 카테고리 api 받는대로 적용 예정

[feature] 헤더 햄버거 메뉴 기능 구현

---

src/components/common/Accordion/Accordion.tsx
src/components/product/AllProducts.tsx
src/components/review/ReviewCard.tsx
src/styles/globals.css

refact: 메인 페이지 css 수정

---

src/app/categories/[categoryId]/page.tsx

file: 카테고리 경로 설정

---

package.json
src/app/(auth)/login/page.tsx
src/app/api/orders/checkout/route.ts
src/app/api/ordersGuest/instant/route.ts
src/app/api/ordersGuest/route.ts
src/app/purchase/layout.tsx
src/app/purchase/page.tsx
src/components/address/Address.tsx
src/components/cart/CartHeader.tsx
src/components/cart/CartItem.tsx
src/components/cart/CartItemForm.tsx
src/components/cart/CartList.tsx
src/components/cart/CartPayForm.tsx
src/components/cart/CartProductList.tsx
src/components/common/Dialog/Dialog.tsx
src/components/common/Tag/Tag.tsx
src/components/product/CartWishlistButtons.tsx
src/components/purchase/PurchaseForm.tsx
src/components/purchase/PurchaseProductsItemList.tsx
src/components/purchase/PurchaseProductsList.tsx
src/components/purchase/PurchaseShoppingInfo.tsx
src/hooks/useCart.tsx
src/services/cartService.ts
src/services/productService.ts
src/services/purchaseService.ts
src/types/purchase/purchaseType.ts
yarn.lock

#139 
어떤 변경 사항이 있나요?
- 비회원 주문, 주문 상세 주문 상품 상세 바로 주문
- 태그 공통 컴포넌트 생성
- Modal 생성
- 다음 우편번호 생성
- yarn install 한번 해야 함.

feature: 비회원 주문, 다음 api, 태그, modal 생성

---

src/components/auth/login/MemberLogin.tsx
src/components/layout/Header/Header.tsx

[fix] 로그인 실패 후 재로그인 시도 시 입력마다 로그인 호출하는 에러 해결

---

src/components/cart/CartItemForm.tsx
src/components/cart/CartPayForm.tsx

fix: vercel 배포 에러 해결

---

src/app/(mypage)/orders/page.tsx
src/app/api/orders/route.ts
src/components/common/Dialog/Dialog.tsx
src/components/common/pagination/Pagination.tsx
src/components/order/OrderList.tsx
src/components/order/OrderListCard.tsx
src/components/order/OrderListPeriodSelect.tsx
src/components/order/OrderWrap.tsx
src/components/order/WriteReviewModal.tsx
src/constants/queryKeys.ts
src/services/orderService.server.ts
src/services/orderService.ts
src/types/orders/orderType.ts

[feature] 주문 목록 조회 페이지 기능 구현

---

src/app/(mypage)/orders/[id]/page.tsx
src/app/guest/[orderNumber]/layout.tsx
src/app/guest/[orderNumber]/page.tsx
src/components/order/OrderDetailWrap.tsx
src/components/order/OrderProductWrap.tsx

[design] 비회원 주문조회 화면 마크업

---

src/app/api/address/add/route.ts
src/app/api/carts/route.ts
src/app/api/orders/checkout/route.ts
src/app/api/orders/checkoutInstant/route.ts
src/app/api/orders/instant/route.ts
src/app/api/orders/route.ts
src/app/purchase-complete/page.tsx
src/app/purchase/page.tsx
src/components/cart/CartItem.tsx
src/components/cart/CartItemForm.tsx
src/components/cart/CartItemList.tsx
src/components/cart/CartPayForm.tsx
src/components/common/NumbericField/NumbericField.tsx
src/components/dialog/NonUserWishDialog.tsx
src/components/product/CartWishlistButtons.tsx
src/components/purchase/PurchaseForm.tsx
src/components/purchase/PurchaseProductsItemList.tsx
src/components/purchase/PurchaseShoppingInfo.tsx
src/hooks/useCart.tsx
src/hooks/useDataMutation.ts
src/services/purchaseService.ts
src/types/cart/cartType.ts

#178
어떤 변경 사항이 있나요?
- 비회원 회원 장바구니 및 주문 테스트 완료
- 전체 구매만 가능하도록 되어 있던 기능 선택한 품목만 구매하도록 수정
- 서버에서 받아온 가격으로 상품 관리 프론트에서 관리하도록 수정
- modal 관련 수정으로 인해 디자이너와 소통 후 수정

fix: 사용자 주문 테스트 및 장바구니 품목 선택 삭제, 선택한 품목만 구매, 전체구매 구현

---

src/components/common/Accordion/Accordion.tsx
src/components/keyword/RealTimeProductComponent.tsx
src/components/product/RealTimeAccordion.tsx
src/mocks/accordionData/accordionData.ts
src/types/realTimeKeyword/realTimeKeywordType.ts

아코디언 컴포넌트 리팩토링
실시간 검색어 아코디언 컴포넌트 분리
어떤 변경 사항이 있나요?

[refact] 아코디언 컴포넌트 리팩토링

---

src/app/(mypage)/orders/[orderNumber]/page.tsx
src/components/order/OrderWrap.tsx
src/services/orderService.server.ts
src/services/orderService.ts

[fix] 주문상세조회 API 변경 반영

---

src/app/api/orders/orderNumber/route.ts
src/app/purchase-complete/page.tsx
src/components/purchase/PurchaseForm.tsx
src/constants/queryKeys.ts
src/services/orderService.ts

#194 
어떤 변경 사항이 있나요?
- 주문 페이지에서 결제 후 백엔드에서 orderId를 받아 주문 완료 페이지 이동 실패 에러 해결

fix: 주문 에러 해결

---

src/app/best/layout.tsx
src/app/best/page.tsx
src/app/sale/layout.tsx
src/app/sale/page.tsx
src/components/order/OrderListCard.tsx

fix: 주문목록에서 제품 클릭시 제품 상세 페이지 연결 수정

---

src/app/(mypage)/mypage/page.tsx
src/components/mypage/UserName.tsx

[design] 마이페이지 홈 사용자 이름 설정, 목데이터 변경

---

src/app/guest/[orderNumber]/page.tsx
src/components/auth/login/GuestOrderCheck.tsx
src/services/orderService.server.ts
src/services/orderService.ts

[feature] 비회원 주문조회 페이지 기능 구현

---

README.md
next.config.ts
src/app/purchase-complete/OrderComplete.tsx
src/components/cart/CartHeader.tsx
src/components/common/Input/Input.tsx
src/components/product/AllProducts.tsx
src/components/product/WishProductLists.tsx
src/components/purchase/PurchaseForm.tsx
src/components/purchase/PurchaseShoppingInfo.tsx
src/services/purchaseService.ts
src/util/formatPhoneNumber.ts

readme 순서 수정 및 기능, 회고 부분 추가
어떤 변경 사항이 있나요?

[fix] readme 수정
